import { NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import connectDB from "@/lib/mongodb";
import Quiz from "@/models/Quiz";
import Course from "@/models/Course";
import { generateAdaptiveQuestion } from "@/lib/rag";
import { Types } from "mongoose";

interface GenerateQuizPayload {
  courseId: string;
  nodeId: string;
  difficulty: "easy" | "medium" | "hard";
  count: number;
}

export async function POST(req: Request) {
  try {
    const session = await requireAuth(); // returns 401 redirect normally, but since this is an API via NextAuth it might just redirect. We should handle it properly if doing fetch.
    // Wait, requireAuth() redirects if no session. For API routes, let's use getSession natively.
    if (!session || !session.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body: GenerateQuizPayload = await req.json();
    const { courseId, nodeId, difficulty, count } = body;

    if (!courseId || !nodeId || !difficulty || !count) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    if (count > 20) {
      return NextResponse.json({ error: "Max generation count is 20" }, { status: 400 });
    }

    await connectDB();

    // Verify course exists
    const course = await Course.findById(courseId).select("title").lean();
    if (!course) {
      return NextResponse.json({ error: "Course not found" }, { status: 404 });
    }

    // Call generateAdaptiveQuestion N times concurrently
    const questionPromises = Array.from({ length: count }).map(() =>
      generateAdaptiveQuestion({
        courseId,
        nodeId,
        difficulty,
        topic: "Core Concept", // Usually you'd fetch the exact node label here
      })
    );

    const generatedQuestions = await Promise.all(questionPromises);

    // Filter out any failed generations (missing required JSON fields)
    const validQuestions = generatedQuestions.filter(
      (q) => q.questionText && q.options && q.options.length >= 2 && q.correctAnswer
    );

    if (validQuestions.length === 0) {
      return NextResponse.json({ error: "Failed to generate valid questions" }, { status: 500 });
    }

    // Map questions to mongoose schema format (adding ObjectIds)
    const finalQuestions = validQuestions.map((q, i) => ({
      _id: new Types.ObjectId(),
      questionText: q.questionText,
      type: q.type,
      options: q.options,
      correctAnswer: q.correctAnswer,
      explanation: q.explanation,
      knowledgeNodeId: q.knowledgeNodeId,
      difficulty: q.difficulty,
      order: i,
    }));

    // Create the Quiz in the DB
    const quiz = await Quiz.create({
      courseId,
      nodeId,
      type: "in-lesson",
      title: `AI Quiz - Node ${nodeId}`,
      questions: finalQuestions,
      isAIGenerated: true,
      isApproved: session.user.role === "instructor", // Auto-approve if generated by instructor
    });

    return NextResponse.json({
      success: true,
      quizId: quiz._id,
      questions: finalQuestions,
    });

  } catch (error: any) {
    console.error("Quiz Generation Error:", error);
    return NextResponse.json(
      { error: "Internal Server Error", details: error.message },
      { status: 500 }
    );
  }
}
